name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # Este passo clona o seu repositório

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          
      # 1. INSTALAR DEPENDÊNCIAS
      - name: Install dependencies
        run: npm ci
        # Ajustado para incluir as duas pastas
        working-directory: ./PrimeiroTestePlaywright/PrimeiroTesteOficial 
          
      # 2. INSTALAR BROWSERS DO PLAYWRIGHT
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        # Ajustado para incluir as duas pastas
        working-directory: ./PrimeiroTestePlaywright/PrimeiroTesteOficial 
          
      # 3. EXECUTAR TESTES
      - name: Run Playwright tests
        run: npx playwright test
        # Ajustado para incluir as duas pastas
        working-directory: ./PrimeiroTestePlaywright/PrimeiroTesteOficial 
          
      # 4. UPLOAD DO RELATÓRIO
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          # O path deve apontar para onde o relatório foi gerado (dentro da pasta de trabalho)
          path: PrimeiroTestePlaywright/PrimeiroTesteOficial/playwright-report/
          retention-days: 30
